name: 'DockerHub mirror'
description: 'GitHub Action to mirror a DockerHub repo to another registry customized'
author: 'Frenchris'
branding:
  color: 'green'
  icon: 'copy'

inputs:
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-password:
    description: 'DockerHub password or persona laccess token'
    required: true
  dockerhub-repo:
    description: 'DockerHub repo to mirror'
    required: true
  dest-registry:
    description: 'Destination registry (eg. ghcr.io)'
    required: true
  dest-repo:
    description: 'Destination repo (eg. username/repo)'
    required: true
  dry-run:
    description: 'Dry run'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - run: |
        set -e
        DOCKERHUB_USERNAME=${{ inputs.dockerhub-username }}
        DOCKERHUB_PASSWORD=${{ inputs.dockerhub-password }}
        DOCKERHUB_REPO=${{ inputs.dockerhub-repo }}
        DOCKER_DEST_REGISTRY=${{ inputs.dest-registry }}
        DOCKER_DEST_REPO=${{ inputs.dest-repo }}
        PUSH_FLAG=""
        echo DOCKERHUB_USERNAME
        echo DOCKERHUB_PASSWORD
        echo DOCKERHUB_REPO
        echo DOCKER_DEST_REGISTRY
        echo DOCKER_DEST_REPO
        echo PUSH_FLAG=""
      shell: bash
